# Use this Dockerfile to build a Debian 11 (Bullseye) version of balenalib while
# there is no such version yet officially.
#
# from https://github.com/balena-io-library/base-images/blob/master/balena-base-images/device-base/raspberrypi3/debian/sid/build/Dockerfile
FROM balenalib/armv7hf-debian:sid-build
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
LABEL io.balena.device-type="raspberrypi3"
RUN echo "deb http://archive.raspbian.org/raspbian bullseye main contrib non-free rpi firmware" >>  /etc/apt/sources.list \
  && apt-key adv --batch --keyserver ha.pool.sks-keyservers.net  --recv-key 0x9165938D90FDDD2E
#  No bullseye repository yet:
#  && echo "deb http://archive.raspberrypi.org/debian bullseye main ui" >>  /etc/apt/sources.list.d/raspi.list \
#  && apt-key adv --batch --keyserver ha.pool.sks-keyservers.net  --recv-key 0x82B129927FA3303E

# hadolint ignore=DL3005,DL3008
RUN apt-get update \
  && apt-get --with-new-pkgs upgrade -y \
  && apt-get install -y --no-install-recommends \
    less \
    libraspberrypi-bin \
    kmod \
    nano \
    net-tools \
    ifupdown \
    iputils-ping \
    i2c-tools \
    usbutils \
  && apt-get autoremove \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
